name: cloudsvc

on: [push, pull_request]

jobs:
  build:
    name: Build cloudsvc

    runs-on: ubuntu-latest

    env:
      GOOS: linux
      GOARCH: amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Go Build
        run: |
          cd oscilloscope/net/cloudsvc
          go mod download
          go build -x -v -trimpath -ldflags "-w -s"
          mkdir out
          cp cloudsvc out/cloudsvc
        shell: bash

      - uses: actions/upload-artifact@v2
        with:
          name: cloudsvc-${{ github.sha }}
          path: oscilloscope/net/cloudsvc/out
