name: pushsvc

on: [push, pull_request]

jobs:
  build-pushsvc:
    name: Build pushsvc

    runs-on: ubuntu-latest

    env:
      GOOS: darwin
      GOARCH: amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Go Build
        run: |
          cd oscilloscope/net/pushsvc
          go mod download
          go build -x -v -trimpath -ldflags "-w -s"
          mkdir out
          cp pushsvc out/pushsvc
        shell: bash

      - uses: actions/upload-artifact@v2
        with:
          name: pushsvc-${{ github.sha }}
          path: oscilloscope/net/pushsvc/out
